baseURL = 'https://manjack1.github.io/'
languageCode = 'en-us'
title = 'ManJack'
theme = 'archie'
copyright = "© ManJack"
paginate = 3
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  mode = "auto"
  useCDN = false
  subtitle = "A minimal and clean blog"
  mathjax = false
  katex = false

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/ManJack1"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "All posts"
    url = "/posts"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 3

  [[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 4
